# Generated by Django 4.2.1 on 2023-05-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_language_start_date_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='award',
            field=models.CharField(default='BSc.', max_length=10),
            preserve_default=False,
        ),
    ]
