# Generated by Django 4.2.1 on 2023-06-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_education_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='still_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='still_work_here',
            field=models.BooleanField(default=False),
        ),
    ]
