# Generated by Django 4.1 on 2023-08-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0008_rename_discipline_education_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="repository",
            field=models.CharField(default="nil", max_length=500),
            preserve_default=False,
        ),
    ]
