"""
Django settings for tower project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # for site and flatpages
    'django.contrib.flatpages',
    'django.contrib.sites',
    # third party
    'crispy_forms',
    'ckeditor',
    'ckeditor_uploader',
    'django_q',
    # local
    'tracker',
    'resume',
]

# for site and flatpages
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tower.urls'

LOGIN_REDIRECT = '/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tower.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
        'NAME': config('DB_NAME', default=BASE_DIR / 'db.sqlite3'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Dont save to database until all is well
DATABASES["default"]["ATOMIC_REQUESTS"] = True

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.UserAttributeSimilarityValidator'),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.MinimumLengthValidator'),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.CommonPasswordValidator'),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.NumericPasswordValidator'),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static_general",
    # BASE_DIR / "frontend"
]
STATIC_ROOT = BASE_DIR / "static"


# media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / "media/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Schedule prescription reminder
Q_CLUSTER = {
    "name": "olaide",
    'timeout': 60,
    'label': 'Django Q',
    'max_attempts': 5,
    "orm": "default",  # Use Django's ORM + database for broker
}

# EMAIL
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#email-backend
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')


CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = "ckeditor/tower/"
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document',
             'items': ['Source',
                       '-',
                       'Save',
                       'NewPage',
                       'Preview',
                       'Print',
                       '-',
                       'Templates']},
            {'name': 'clipboard',
             'items': ['Cut',
                       'Copy',
                       'Paste',
                       'PasteText',
                       'PasteFromWord',
                       '-',
                       'Undo',
                       'Redo']},
            {'name': 'editing', 'items': [
                'Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': [
                'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea',
                'Select', 'Button', 'ImageButton', 'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': [  # 'EqnEditor',
                 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript',
                 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': [
                'NumberedList', 'BulletedList', '-', 'Outdent',
                'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                'JustifyLeft', 'JustifyCenter', 'JustifyRight',
                'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': [
                'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley',
                'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': [
                'Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
            {'name': 'math', 'items': ['Mathjax', ]},
        ],
        'specialChars': [
            '!', '&quot;', '#', '$', '%', '&amp;', "'", '(', ')',
            '*', '+', '-', '.', '/',
            '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';',
            '&lt;', '=', '&gt;', '?', '@',
            'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K',
            'L', 'M', 'N', 'O',
            'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
            '[', ']', '^', '_', '`',
            'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k',
            'l', 'm', 'n', 'o', 'p',
            'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
            '{', '|', '}', '~',
            '&euro;', '&lsquo;', '&rsquo;', '&ldquo;', '&rdquo;',
            '&ndash;', '&mdash;', '&iexcl;', '&cent;', '&pound;',
            '&curren;', '&yen;', '&brvbar;', '&sect;', '&uml;',
            '&copy;', '&ordf;', '&laquo;', '&not;', '&reg;', '&macr;',
            '&deg;', '&sup2;', '&sup3;', '&acute;', '&micro;', '&para;',
            '&middot;', '&cedil;', '&sup1;', '&ordm;', '&raquo;',
            '&frac14;', '&frac12;', '&frac34;', '&iquest;', '&Agrave;',
            '&Aacute;', '&Acirc;', '&Atilde;', '&Auml;', '&Aring;',
            '&AElig;', '&Ccedil;', '&Egrave;', '&Eacute;', '&Ecirc;',
            '&Euml;', '&Igrave;', '&Iacute;', '&Icirc;', '&Iuml;',
            '&ETH;', '&Ntilde;', '&Ograve;', '&Oacute;', '&Ocirc;',
            '&Otilde;', '&Ouml;', '&times;', '&Oslash;', '&Ugrave;',
            '&Uacute;', '&Ucirc;', '&Uuml;', '&Yacute;', '&THORN;',
            '&szlig;', '&agrave;', '&aacute;', '&acirc;', '&atilde;',
            '&auml;', '&aring;', '&aelig;', '&ccedil;', '&egrave;',
            '&eacute;', '&ecirc;', '&euml;', '&igrave;', '&iacute;',
            '&icirc;', '&iuml;', '&eth;', '&ntilde;', '&ograve;',
            '&oacute;', '&ocirc;', '&otilde;', '&ouml;', '&divide;',
            '&oslash;', '&ugrave;', '&uacute;', '&ucirc;', '&uuml;',
            '&yacute;', '&thorn;', '&yuml;', '&OElig;', '&oelig;',
            '&#372;', '&#374', '&#373', '&#375;', '&sbquo;', '&#8219;',
            '&bdquo;', '&hellip;', '&trade;', '&#9658;', '&bull;',
            '&rarr;', '&rArr;', '&hArr;', '&diams;', '&asymp;', '&alpha;',
            '&beta;', '&gamma;', '&delta;', '&epsilon;',
            '&zeta;', '&eta;', '&theta;', '&iota;', '&kappa;', '&lambda;',
            '&mu;', '&nu;', '&xi;', '&omicron;', '&pi;',
            '&rho;', '&sigma;', '&tau;', '&upsilon;', '&phi;', '&chi;',
            '&psi;', '&omega;', '&divide;', '&#9651;', '&#8869;',
            '&#8773;', '&#8774;', '&#8373;', '&#8358;', '&#8211;',
            '&#8722;', '&#440;', '&#8230;', '&#8216;', '&#8217;',
            '&prime;', '&#8220;', '&#8221;', '&#601;', '&#257;', '&#281;',
            '&#8728;', '&#10234;', '&#8706;', '&#241;',
            '&#7778;', '&#507;', '&#7696;', '&#7717;', '&#363;', '&#8462;',
            '&#299;', '&#650;', '&#8455;', '&#658;',
            '&#652;', '&#618;', '&#712;', '&#720;', '&#596;', '&#594;',
            '&#593;', '&#643;', '&#716;', '&#331;', '&#240;',
            '&#8651;', '&harr;', '&ne;', '&radic;', '&odash;', '&otimes;'
        ],
        # put selected toolbar config here
        'toolbar': 'YourCustomToolbarConfig',
        'toolbarGroups': [
            {
                'name': 'document',
                'groups': ['mode', 'document', 'doctools']}],
        'height': 291,
        'width': '100%',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
        'toolbarCanCollapse': True,
        # mathjax display
        'allowedContent': True,
        # dont convert html entities
        'entities_processNumerical': 'force',
        'forceSimpleAmpersand': True,
        # 'entities_latin': True,
        'Mathjax': {
            'tex': {
                'inlineMath': [['$', '$'], ['\\(', '\\)']]
            },
            'svg': {
                'fontCache': 'global'
            }
        },
        'mathJaxLib': (
            '//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js'
            '?config=TeX-AMS_HTML'),
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'entities',
            'autogrow',
            'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'mathjax',
        ]),
    }
}
