# Generated by Django 4.2.1 on 2023-05-24 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='medication name', max_length=250)),
                ('description', models.TextField(blank=True, help_text='What the medication is meant for', null=True)),
                ('dosage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('dosage_unit', models.CharField(max_length=50)),
                ('frequency', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('frequency_period', models.CharField(choices=[('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month')], max_length=7)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('track_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.prescriptionuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
