# Generated by Django 4.2.1 on 2023-06-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_prescription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='total_dosage_unit_quantity',
            field=models.IntegerField(default=1, help_text='how many units of the dosage_unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage_unit',
            field=models.CharField(help_text='e.g: ml, capsule, tablet, shot', max_length=50),
        ),
    ]
